=== Anaksimandar/Projekat1_NRT_145_19/oglasi.dtd
<!ELEMENT Oglasi (Oglas+)>
<!ELEMENT Oglas(id,KategorijaOglasa,DatumIsteka,TekstOglasa,Cena,Oznaka,Email)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT KategorijaOglasa (#PCDATA)>
<!ELEMENT DatumIsteka (#PCDATA)>
<!ELEMENT TekstOglasa (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Oznaka (Tag+)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Email (mail+)>
<!ELEMENT mail (#PCDATA)>

<!ATTLIST Cena valuta (rsd|eur|rub) #REQUIRED>
<!ATTLIST mail tip (privatni|poslovni) "privatni">

=== Anaksimandar/Projekat1_NRT_145_19/oglasi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Oglasi SYSTEM "oglasi.dtd">
<Oglasi>
    <Oglas>
        <id>1<id>
        <KategorijaOglasa>muzicki instrument</KategorijaOglasa>
        <DatumIsteka>2022-01-12</DatumIsteka>
        <TekstOglasa>Prodajem gitaru ...</TekstOglasa>
        <Cena valuta="rsd">15000</Cena>
    </Oglas>
    <Oznaka>
        <Tag>gitara</Tag>
        <Tag>fender</Tag>
    </Oznaka>
    <Email>
            <mail tip="privatni">analo12223@gmail.com<mail/>
            <mail tip="poslovni">aleksandar00@gmail.com<mail/>
        </Email>
    <Oglas>
        <id>2</id>
        <KategorijaOglasa>Odeca</KategorijaOglasa>
        <DatumIsteka>2022-05-10</DatumIsteka>
        <TekstOglasa>Prodajem majicu ...</TekstOglasa>
        <Cena valuta="eur">20</Cena>
    </Oglas>
    <Oznaka>
        <Tag>majica</Tag>
        <Tag>umbro</Tag>
    </Oznaka>
    <Email>
            <mail tip="privatni">analo12223@gmail.com<mail/>
            <mail tip="poslovni">aleksandar00@gmail.com<mail/>
        </Email>
</Oglasi>
